# Site settings
title: Scott-tastic
email: s.j.maclell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, stories and other other development fun about shipping software
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smaclell.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  smaclell

# Build settings
markdown: kramdown

paginate: 10
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'style.scss']
